### ISSUE TITLE
Initialize Firebase DB

### ISSUE THREAD

**Issue by jscampbell43** [jscampbell43/Project3_Group12_Frontend#2]
Create FirebaseDB database and Repositories 
Setup the Firebase DB
Create the DAO for the DB
How will it be tested:
Instrumented test of Android App with Firebase Test Lab.
https://firebase.google.com/docs/test-lab/

**Comment by Mhaidar117** [comment]
Firebase has been connected. Here is the link to our firestore database. If you click Data on the top left you can see two users were added as tests
https://console.firebase.google.com/project/fila-8f418/firestore/data/~2Fusers~2Fi3vJyXdugUe7iZMz5EBY

**Comment by Mhaidar117** [comment]
Firebase has been connected. Here is the link to our firestore database. If you click Data on the top left you can see two users were added as tests
https://console.firebase.google.com/project/fila-8f418/firestore/data/~2Fusers~2Fi3vJyXdugUe7iZMz5EBY
